### PR TITLE
Fix Influx upload when querying multiple metrics at the same time

### PR DESCRIPTION
**Pull request by shadowpanther**

### CODE REVIEW

**Comment by qvr** [comment]
Hi, thanks!

Apparently I had not actually tested writing multiple metrics to influx, your change looks good.

Can you squash the commits so that there would be one commit for the config rename and gitignore, and other one for the influx fix?

**Comment by shadowpanther** [comment]
Yeah, if I figure out how to do that.

**Comment by shadowpanther** [comment]
Well, there are now two commits that do the proper job, for old commits and one merge. I'm not sure how to proceed from here.

**Comment by qvr** [comment]
I merged the 2 commits in e190497, thanks!

**Pull request closed without merging**
